name: Hello world workflow
on: 
  Push: 
   branches:
      -main
  pull_request:
    branches:
       -main
  workflow_dispatch:
jobs:
    hello:
      runs-on: ubuntu-latest
       steps:
          - uses: actions/checkout@v2
          -name: hello world
          run: echo "Hello world"
          shell: bash
    googbye:
      runs-on: ubuntu-latest
       steps:
          -name: goodbye world
          run: echo "goodbye world"
          shell: bash
          
          
    
      
     
